# Generated by Django 6.1.1 on 2026-10-04 20:59

import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('sub', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('mobile', models.CharField(max_length=11, unique=True, validators=[django.core.validators.RegexValidator('^09\\d{9}$')])),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('role', models.CharField(choices=[('student', 'Student'), ('consultant', 'Consultant'), ('professor', 'Professor'), ('admin', 'Admin')], max_length=20)),
                ('consultant_type', models.CharField(blank=True, choices=[('consultant', 'Consultant'), ('top_ranker', 'Top Ranker')], max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('identity_synced_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('field_of_study', models.CharField(blank=True, choices=[('experimental', 'Experimental'), ('mathematics', 'Mathematics'), ('humanities', 'Humanities')], max_length=20)),
                ('avatar_url', models.URLField(blank=True)),
                ('bio', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('last_name', 'first_name'),
            },
        ),
    ]
