# Generated by Django 6.1.1 on 2026-10-09 22:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceEntry',
            fields=[
                ('key', models.CharField(help_text='Stable identifier, <panel>.<name>. Never change it once groups use it.', max_length=64, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator('^(student|consultant|professor|admin)\\.[a-z0-9]+(-[a-z0-9]+)*$', 'Use <panel>.<name-with-dashes>.')])),
                ('panel', models.CharField(choices=[('student', 'Student'), ('consultant', 'Consultant'), ('professor', 'Professor'), ('admin', 'Admin')], max_length=20)),
                ('title_fa', models.CharField(max_length=120, verbose_name='title (Persian)')),
                ('title_en', models.CharField(max_length=120, verbose_name='title (English)')),
                ('description', models.CharField(blank=True, max_length=300)),
                ('button_label', models.CharField(default='ورود به سرویس', max_length=60)),
                ('icon', models.CharField(blank=True, max_length=40)),
                ('order', models.PositiveSmallIntegerField(help_text='Position in the panel, smallest first.')),
                ('target_url', models.URLField(blank=True, help_text='Where the service lives. Empty means it is not connected yet.', max_length=500)),
                ('mode', models.CharField(choices=[('redirect', 'Redirect'), ('embed', 'Embed')], default='redirect', max_length=10)),
                ('enabled', models.BooleanField(default=True)),
                ('owner_group', models.PositiveSmallIntegerField(blank=True, help_text='Group number.', null=True, validators=[django.core.validators.MinValueValidator(1)])),
            ],
            options={
                'verbose_name_plural': 'service entries',
                'ordering': ('panel', 'order', 'key'),
                'indexes': [models.Index(fields=['panel', 'order'], name='registry_se_panel_2ed906_idx')],
            },
        ),
    ]
