# Generated by Django 6.1.1 on 2026-10-09 22:08

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentBlock',
            fields=[
                ('key', models.CharField(choices=[('landing.footer', 'landing.footer'), ('landing.hero', 'landing.hero'), ('landing.missions', 'landing.missions'), ('landing.navbar', 'landing.navbar'), ('landing.rankers', 'landing.rankers'), ('landing.statistics', 'landing.statistics'), ('landing.teachers', 'landing.teachers'), ('landing.testimonials', 'landing.testimonials'), ('widget.experience_feed', 'widget.experience_feed'), ('widget.study_streak', 'widget.study_streak'), ('widget.welcome', 'widget.welcome')], max_length=64, primary_key=True, serialize=False)),
                ('data', models.JSONField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('key',),
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('body', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='accounts.profile')),
            ],
            options={
                'ordering': ('-created_at', '-id'),
                'indexes': [models.Index(fields=['profile', '-created_at'], name='panels_noti_profile_33761f_idx')],
            },
        ),
    ]
